---
- hosts: all
  become: yes
  tasks:
  - name: install tree
    aptt:
     name: tree
     state: present
    ignore_errors: yes
    
  - name: install tree
    yum:
     name: httpd
     state: present   